
server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8080
    
spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/product_recommendation
    username: postgres
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    open-in-view: false